### ISSUE TITLE
Colorization Milestone 1

### ISSUE THREAD

**Issue by xenophile127** [xenophile127/FFA-Disassembly#18]
**Objective:** At least as good BIOS auto colorization.

* Run as GBC game with palettes loaded:
  - [x]  Identify as a GBC game.
  - [x]  Change init to load palettes at startup, identical to BIOS.
    * Sprite palette includes red and blue.
    * Background palette is black, white, blue, green.

* Some sprites use a blue palette and some sprites use a red palette:
  - [x]  Assign sprites to different palettes.
    * Player.
    * Player Attack.
    * Snowman. (Could give it its final palette.)
    * NPC Companion (and their projectile).
    * Enemy Projectile.
    * Enemy/NPC 1,2,&3.

* HBlank effects:
  - [x]  HUD
  - [x] Intro scroll
  - [x] Shutter
  - [x] Shutter Dark
  - [x] Letterbox
  - [x] Any of these (like Shutter) that turn off the LCD will use the second BG.

* Other effects:
  - [x] Blind status effect.
    * For now, need one palette for sprite and one for background.
    * What about a custom Dark palette for each?
  - [x] Screen flash.
  - [x] Boss blink effect.
    * VBlank: Blink blue palette on boss hit.
      * This will necessitate loading that sprite palette at VBLank.
      * Best option is to hard-code a "blink" palette. Maybe make all palettes sets actually nine palettes?
  - [x] Fade effect.
    * Similar changes have been completed for Super Game Boy.
