### ISSUE TITLE
Colorization Milestone 2

### ISSUE THREAD

**Issue by xenophile127** [xenophile127/FFA-Disassembly#20]
**Objective:** Dynamic sprites (except bosses) with full-color palettes as required by testing.

* NPC palettes:
  - [x] Load NPC palettes when spawned.
  - [x] Chests load a palette if spawned from a script.
  - [x] Chests dropped by an enemy use the palette of their dropping enemy
  - [x] Enemy defeated explosions use the palette of the defeated enemy.
  - [x] Fix bug when loading NPCs while faded.

* Player palettes:
  - [x] Load player palette when changing form:
    * Chocobo.
    * Chocobot.
    * Chocoboat.
  - [x] Load player palette when afflicted by status:
    *  ~~Blind~~. (The Blind effect operates on *all* palettes. No changes are necessary.)
    * Moogle.
    * Poison.
    * Stone.
  - [x] ~~Load player palette when riding mine cart.~~ (Not needed.)

* Player attacks:
  - [x] Load attack palette when using a weapon/spell/item.
  - [x] Reuse attack palette for menu fingers and trash can.
  - [x] Reuse attack palette for Map flashing marker.
  - [x] Reuse attack palette for script special effects.

* Enemy attacks:
  - [x] Load enemy projectile palette when an enemy is spawned.
  - [x] ~~Resolve conflicts when two different enemy projectile types are used on the same screen.~~ (Will address on a case-by-case basis.)

* Bosses:
  - [x] Create minimal boss palettes to resolve issues caused by NPCs.
