### ISSUE TITLE
Colorization Milestone 3

### ISSUE THREAD

**Issue by xenophile127** [xenophile127/FFA-Disassembly#30]
**Objective:** Limited background colorization: two palettes--default GBC palette with green and blue, and MQ (Mystic Quest) default GBC palette with green and dark green. Continue colorizing sprites and fixing issues (currently colorized through about Wendel).

* Background Palettes Code:
  - [x] Add four raw tile attributes to each metatile in `src/data/metatiles.asm`
  - [x] Load tile attributes in addition to tile ids when drawing.
  - [x] Windows backup/change/restore tile attributes.
  - [x] Fix ending letterbox.

* Background Palettes:
  - [x]  Blue for sky, water (docs and bridges?), and the crystals in the desert.
  - [x]  Green for trees, Manaland foliage, and the sprout.
  - [x] Use default colors for most tiles. (Change to MQ green instead of GBC green/blue.)
  - [x] Test with gray windows.

* Effects:
  - [x] Use gray for intro scroll fade.

* Sprites:
  - [x] Backup palettes when loading a boss and restore after the boss.
  - [x] Finish layout changes to Jackal and Golem.
  - [x] Finish layout changes to Vampire.
  - [x] Set palettes for Wendel villagers.
  - [x] Set palettes for dwarves.
  - [x] Set palettes for Mithril Mine monsters.
  - [x] Set palettes for Megapede.
